#!/usr/bin/env bash
#
#   TODO: add Kerberos support
#
#   Installing CDH4 with MRv1 on a Single Linux Node in Pseudo-distributed mode 
#   http://www.cloudera.com/content/cloudera/en/documentation/cdh4/latest/CDH4-Quick-Start/cdh4qs_topic_3_2.html
#

usage() {

    [ -z ${RERUN_COMMAND_DIR} ] && {
        echo "usage: ${0} <options>"
    } || {
        echo "usage: ./rerun cdh-deploy:config-cdh4-pseudo-single-node-mr1 <options>"
    }
    echo "    --run:    run basic MR1 configuration of CDH4 Pseudo distributed Single node cluster"
    [ ! -z ${RERUN_COMMAND_DIR} ] && {
        echo "    --export-to=<directory>: export config script to <directory>"
        echo 
        echo "Note: only one option can be defined"
    }
    echo
}

check_service() {

    local _SERVICENAME=${1}

    pgrep -f "java -Dproc_${_SERVICENAME}" 2>&1 > /dev/null && {
        echo "- The service ${_SERVICENAME} was started successfully"
    } || {
        echo "Error! The service ${_SERVICENAME} was not started"
        exit 1
    }
}

export_to() {

    local _TARGET_DIR=${1}

    [ -z ${RERUN_COMMAND_DIR} ] && {
        echo "Error! Export can be done only in rerun environment"
        exit 1
    }

    echo "- Exporting '${RERUN_COMMAND_DIR}' to '${_TARGET_DIR}'"
    [ ! -d "${_TARGET_DIR}" ] && {
        mkdir -p "${_TARGET_DIR}"
    }
    cp "${RERUN_COMMAND_DIR%%/}"/* "${_TARGET_DIR%%/}/" 

    echo "- Export completed"
}

create_mapreduce_dirs() {

    echo "- Creating /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
    echo "- Changing rights for /var/lib/hadoop-hdfs/cache/mapred/mapred/staging" && \
        sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging && \
        sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred && \
    {
        echo "- The MapReduce system directories are created successfully"
    } || {
        echo "Error! The MapReduce system directories were not created"    
        exit 1
    }
}

start_mapreduce() {

    for x in `cd /etc/init.d ; ls hadoop-0.20-mapreduce-*` ; do sudo service $x start ; done

    check_service jobtracker
    check_service tasktracker
}

config() {

    # Create the MapReduce system directories
    create_mapreduce_dirs

    # Start MapReduce 
    start_mapreduce
}

# ==============================================
#   Main script
# ----------------------------------------------

[ "$#" -eq 0 ] && {
    usage
}

# Get the options
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        # options without arguments
        # options with arguments   
        --run)
            config
            exit 0
            ;;
        --export-to)
            export_to "$2"
            exit 0
            ;;
        *)
            break
            ;;   
    esac
    shift
done
